### PR TITLE
rm diffeqoperators

### PR DESCRIPTION
**Pull request by vpuri3**
another downstream error from https://github.com/SciML/DiffEqBase.jl/pull/870

### CODE REVIEW

**Comment by vpuri3** [comment]
@xtalax can the brusselerator problem use MOL?

**Comment by vpuri3** [comment]
https://github.com/SciML/DiffEqProblemLibrary.jl/blob/master/lib/ODEProblemLibrary/src/brusselator_prob.jl#L100-L103

**Comment by xtalax** [comment]
yes, we have a bruss example in the tests

**Comment by xtalax** [comment]
this should stay in the problem library though, important to keep examples around

**Comment by vpuri3** [comment]
can we do it without DEO?

**Comment by vpuri3** [comment]
let's remove the brusselator problem from this package temporarily. we should redo it with methodoflines.

**Comment by ChrisRackauckas** [comment]
Add the bruss from https://docs.sciml.ai/DiffEqDocs/stable/tutorials/advanced_ode_example/

**Comment by xtalax** [comment]
See also https://github.com/SciML/MethodOfLines.jl/blob/v0.8.1/test/pde_systems/brusselator_eq.jl

**Pull request closed without merging**
