### PR TITLE
no deo bruss (was wrong anyway)

### PR DESCRIPTION
**Pull request by xtalax**

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
tests failed

**Comment by xtalax** [comment]
I'm not going to format DAEProblemLibrary.jl, current is clearer

**Comment by vpuri3** [comment]
@ChrisRackauckas can you merge and bump version? I will run CI on https://github.com/JuliaDiff/SparseDiffTools.jl/pull/212 then.

**Comment by vpuri3** [comment]
@ChrisRackauckas can you merge and bump version please? I will rerun https://github.com/SciML/DiffEqBase.jl/pull/870 then.

**Pull request merged**
